import { AchievementDefinition } from '@/src/types/achievements';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'workouts_1',
    title: 'First Step',
    description: 'Complete your first workout.',
    category: 'workout',
    icon: 'fitness',
    color: '#FF6B35',
    points: 10,
    metric: 'totalWorkouts',
    threshold: 1,
  },
  {
    id: 'workouts_10',
    title: 'Getting Serious',
    description: 'Complete 10 workouts.',
    category: 'workout',
    icon: 'barbell',
    color: '#FF6B35',
    points: 25,
    metric: 'totalWorkouts',
    threshold: 10,
  },
  {
    id: 'distance_5',
    title: 'On the Move',
    description: 'Reach 5 km total distance.',
    category: 'steps',
    icon: 'walk',
    color: '#2E86AB',
    points: 15,
    metric: 'totalDistanceKm',
    threshold: 5,
  },
  {
    id: 'duration_120',
    title: 'Two Hours In',
    description: 'Accumulate 120 minutes of activity.',
    category: 'consistency',
    icon: 'time',
    color: '#00B894',
    points: 20,
    metric: 'totalDurationMinutes',
    threshold: 120,
  },
  {
    id: 'xp_100',
    title: 'Leveling Up',
    description: 'Earn 100 XP.',
    category: 'rewards',
    icon: 'trophy',
    color: '#FDCB6E',
    points: 20,
    metric: 'xp',
    threshold: 100,
  },
];
